/**
 * Company — a business space inside OmniOS.
 *
 * A company is intentionally thin. It holds identity and DNA; everything a
 * company *does* lives in scoped records (tasks, KPIs, finance entries…) that
 * the Capability registry renders. That is what lets "create a company" produce
 * a complete, working headquarters without writing any company-specific code.
 */

import type { Timestamp } from './work';
import type { Money } from './work';

export const COMPANY_STAGES = [
  'idea',
  'validating',
  'building',
  'operating',
  'scaling',
  'paused',
] as const;
export type CompanyStage = (typeof COMPANY_STAGES)[number];

/** A company's identity — the part a founder writes once and edits rarely. */
export interface CompanyDNA {
  readonly mission: string;
  readonly vision: string;
  readonly purpose: string;
  readonly values: readonly string[];
  readonly businessModel: string;
  readonly targetAudience: readonly AudienceSegment[];
  readonly competitors: readonly Competitor[];
  readonly longTermStrategy: string;
  readonly moat?: string;
}

export interface AudienceSegment {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly pains: readonly string[];
}

export interface Competitor {
  readonly id: string;
  readonly name: string;
  readonly positioning: string;
  readonly threat: 'low' | 'medium' | 'high';
}

/** Brand identity. Shared shape with the personal brand so Creative Studio needs one code path. */
export interface BrandDNA {
  readonly voice: readonly string[];
  readonly tone: string;
  readonly palette: readonly BrandColor[];
  readonly typography: string;
  readonly imagery: string;
  readonly doNot: readonly string[];
  readonly taglines: readonly string[];
}

export interface BrandColor {
  readonly name: string;
  readonly value: string;
  readonly role: 'primary' | 'secondary' | 'surface' | 'accent';
}

export interface ExpansionPlan {
  readonly id: string;
  readonly market: string;
  readonly rationale: string;
  readonly status: 'considering' | 'preparing' | 'entering' | 'live' | 'rejected';
  readonly horizon: string;
}

export interface Company {
  readonly id: string;
  readonly name: string;
  readonly shortName: string;
  readonly description: string;
  readonly industry: string;
  readonly stage: CompanyStage;
  readonly createdAt: Timestamp;
  readonly updatedAt: Timestamp;
  readonly baseCurrency: Money['currency'];
  readonly dna: CompanyDNA;
  readonly brand: BrandDNA;
  readonly expansion: readonly ExpansionPlan[];
  /** Capabilities switched off for this company. Empty means "all of them", which is the default. */
  readonly disabledCapabilityIds: readonly string[];
  /** Set when the record was generated by the Create Company flow rather than hand-authored. */
  readonly generated: boolean;
  readonly archivedAt?: Timestamp;
}

/** The founder-supplied half of company creation. Everything else is generated. */
export interface CompanyDraft {
  readonly name: string;
  readonly description: string;
  readonly industry: string;
  readonly mission: string;
  readonly vision: string;
  readonly businessModel: string;
  readonly goals: readonly string[];
  readonly stage: CompanyStage;
  readonly baseCurrency: Money['currency'];
}
