/**
 * The specialist roster.
 *
 * The founder never picks from this list — they talk to one assistant. This exists
 * so the assistant has somewhere to delegate, and so the founder can *audit* who
 * was consulted after the fact. Adding a specialist is a data change; the router
 * scores declaratively against `matches` and needs no new branches.
 */

import type { SpecialistAgent } from '@/lib/domain';

export const SPECIALISTS: readonly SpecialistAgent[] = [
  {
    id: 'chief-of-staff',
    name: 'Chief of Staff',
    domain: 'executive',
    role: 'Prioritisation and conflict resolution',
    charter:
      'Holds the whole picture. Resolves collisions between time, money, energy and health before they become a bad week.',
    capabilityIds: ['executive', 'operations', 'life-ops'],
    matches: [
      'priority',
      'prioritise',
      'prioritize',
      'what should i do',
      'focus',
      'plan my',
      'my week',
      'this week',
      'schedule',
      'overwhelmed',
      'balance',
      'conflict',
      'decide',
      'decision',
      'today',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: [
      'Rank open work across every space against goals and available energy',
      'Name the one thing that unblocks the most other things',
      'Flag commitments that collide before they are made',
    ],
  },
  {
    id: 'strategist',
    name: 'Strategist',
    domain: 'strategy',
    role: 'Direction, positioning and sequencing',
    charter: 'Asks whether the plan is still the right plan, and what would prove it wrong.',
    capabilityIds: ['strategy', 'research'],
    matches: [
      'strategy',
      'strategic',
      'positioning',
      'roadmap',
      'vision',
      'long term',
      'expand',
      'expansion',
      'market entry',
      'moat',
      'competitor',
      'goal',
      'okr',
      'quarter',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: [
      'Pressure-test goals against capacity and cash',
      'Sequence expansion so one market funds the next',
      'Surface the assumption whose failure costs the most',
    ],
  },
  {
    id: 'marketer',
    name: 'Marketing Lead',
    domain: 'marketing',
    role: 'Demand, channels and campaigns',
    charter: 'Turns positioning into attention, and attention into a repeatable channel.',
    capabilityIds: ['marketing', 'creative'],
    matches: [
      'marketing',
      'campaign',
      'launch',
      'audience',
      'funnel',
      'acquisition',
      'growth',
      'ads',
      'advertis',
      'newsletter',
      'content calendar',
      'positioning',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: [
      'Draft a campaign with channel, message and success metric',
      'Identify the channel with the best evidence behind it',
      'Kill campaigns that have stopped compounding',
    ],
  },
  {
    id: 'social',
    name: 'Social Lead',
    domain: 'social',
    role: 'Platform-native content and cadence',
    charter: 'Keeps the drumbeat going without turning the brand into noise.',
    capabilityIds: ['marketing', 'creative'],
    matches: ['social', 'instagram', 'linkedin', 'tiktok', 'youtube', 'post', 'reel', 'thread'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: [
      'Turn one idea into a platform-appropriate set of posts',
      'Hold a posting cadence that survives a busy week',
    ],
  },
  {
    id: 'copywriter',
    name: 'Copywriter',
    domain: 'marketing',
    role: 'Words that carry the brand',
    charter: 'Writes in the space’s voice, not a generic one.',
    capabilityIds: ['marketing', 'branding', 'creative'],
    matches: ['copy', 'write', 'headline', 'tagline', 'email', 'landing page', 'wording', 'tone'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Draft copy bound to the Brand DNA in force', 'Offer three angles, not one'],
  },
  {
    id: 'seo',
    name: 'Search Lead',
    domain: 'marketing',
    role: 'Discoverability',
    charter: 'Makes the thing findable by the people already looking for it.',
    capabilityIds: ['marketing', 'research'],
    matches: ['seo', 'search', 'keyword', 'ranking', 'organic', 'backlink'],
    allowedScopeKinds: ['company'],
    wouldDo: ['Map intent to pages', 'Find the queries with demand and no good answer'],
  },
  {
    id: 'sales',
    name: 'Sales Lead',
    domain: 'sales',
    role: 'Pipeline and conversion',
    charter: 'Moves conversations forward, and closes the ones that are ready.',
    capabilityIds: ['sales'],
    matches: ['sales', 'pipeline', 'lead', 'deal', 'client', 'customer', 'proposal', 'quote', 'crm'],
    allowedScopeKinds: ['company'],
    wouldDo: [
      'Rank the pipeline by what is actually closeable',
      'Name the follow-up that has gone cold',
    ],
  },
  {
    id: 'engineer',
    name: 'Engineer',
    domain: 'development',
    role: 'Implementation',
    charter: 'Ships the smallest working slice, then makes it good.',
    capabilityIds: ['development', 'automation'],
    matches: [
      'code',
      'build',
      'implement',
      'bug',
      'feature',
      'deploy',
      'refactor',
      'api',
      'database',
      'test',
      'ship',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Break a feature into shippable slices', 'Diagnose a failure from the evidence'],
  },
  {
    id: 'architect',
    name: 'Architect',
    domain: 'development',
    role: 'System design',
    charter: 'Chooses the structure that will still be right in a year.',
    capabilityIds: ['development'],
    matches: ['architecture', 'design system', 'scale', 'schema', 'migration', 'infrastructure'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Name the decision that is expensive to reverse', 'Reject premature abstraction'],
  },
  {
    id: 'qa',
    name: 'Quality Lead',
    domain: 'development',
    role: 'Verification',
    charter: 'Believes nothing until it has been run.',
    capabilityIds: ['development'],
    matches: ['test', 'qa', 'regression', 'verify', 'quality', 'broken'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Define what "done" has to prove', 'Find the case nobody tried'],
  },
  {
    id: 'security',
    name: 'Security Lead',
    domain: 'security',
    role: 'Exposure and hardening',
    charter: 'Assumes someone hostile is reading this.',
    capabilityIds: ['development', 'legal', 'operations'],
    matches: ['security', 'secret', 'credential', 'breach', 'privacy', 'gdpr', 'access', 'token'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Map what would leak and how', 'Insist on a boundary before an integration'],
  },
  {
    id: 'cfo',
    name: 'Finance Lead',
    domain: 'finance',
    role: 'Cash, margin and runway',
    charter: 'Counts honestly, forecasts conservatively, and says when the maths does not work.',
    capabilityIds: ['finance'],
    matches: [
      'finance',
      'money',
      'revenue',
      'cost',
      'profit',
      'margin',
      'cash',
      'cash flow',
      'runway',
      'budget',
      'invoice',
      'forecast',
      'price',
      'pricing',
      'tax',
      'spend',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: [
      'Reconcile committed spend against forecast',
      'Flag the month where cash gets tight',
    ],
  },
  {
    id: 'legal',
    name: 'Legal Counsel',
    domain: 'legal',
    role: 'Obligations and exposure',
    charter: 'Names the clause that matters before it matters.',
    capabilityIds: ['legal'],
    matches: ['legal', 'contract', 'terms', 'liability', 'compliance', 'licence', 'license', 'nda'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Summarise obligations in plain language', 'Flag where a lawyer is genuinely needed'],
  },
  {
    id: 'brand',
    name: 'Brand Lead',
    domain: 'branding',
    role: 'Identity and consistency',
    charter: 'Protects the voice across everything the space produces.',
    capabilityIds: ['branding', 'creative'],
    matches: ['brand', 'identity', 'logo', 'voice', 'palette', 'typography', 'style guide'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Hold output to the Brand DNA', 'Say no to off-voice work'],
  },
  {
    id: 'designer',
    name: 'Designer',
    domain: 'design',
    role: 'Visual and interface craft',
    charter: 'Makes the thing feel considered rather than assembled.',
    capabilityIds: ['creative', 'development', 'branding'],
    matches: ['design', 'ui', 'ux', 'layout', 'visual', 'mockup', 'figma', 'interface'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Turn a brief into a concrete layout', 'Reduce before adding'],
  },
  {
    id: 'video',
    name: 'Video Producer',
    domain: 'video',
    role: 'Moving image',
    charter: 'Cuts for attention without cheapening the brand.',
    capabilityIds: ['creative', 'marketing'],
    matches: ['video', 'reel', 'edit', 'footage', 'shoot', 'storyboard', 'motion'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Storyboard from a brief', 'Specify shots, pacing and cut points'],
  },
  {
    id: 'photographer',
    name: 'Photographer',
    domain: 'photography',
    role: 'Stills and product imagery',
    charter: 'Consistent light, consistent world.',
    capabilityIds: ['creative'],
    matches: ['photo', 'photography', 'product shot', 'image', 'lighting', 'retouch'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Define a shot list', 'Keep imagery consistent across a catalogue'],
  },
  {
    id: 'researcher',
    name: 'Researcher',
    domain: 'research',
    role: 'Evidence gathering',
    charter: 'Finds out instead of guessing, and says which it was.',
    capabilityIds: ['research', 'strategy', 'learning'],
    matches: [
      'research',
      'find out',
      'investigate',
      'compare',
      'evaluate',
      'benchmark',
      'landscape',
      'paper',
      'study',
      'learn',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Separate what is known from what is assumed', 'Return sources, not vibes'],
  },
  {
    id: 'analyst',
    name: 'Data Analyst',
    domain: 'data',
    role: 'Numbers and anomalies',
    charter: 'Answers with the number, its trend, and how much to trust it.',
    capabilityIds: ['finance', 'strategy', 'marketing', 'sales'],
    matches: ['analys', 'metric', 'kpi', 'trend', 'number', 'report', 'dashboard', 'anomaly', 'data'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Find the metric that actually moved', 'Distrust a spike until it repeats'],
  },
  {
    id: 'operator',
    name: 'Operations Lead',
    domain: 'operations',
    role: 'Process and throughput',
    charter: 'Turns a thing that worked once into a thing that works every time.',
    capabilityIds: ['operations', 'hr'],
    matches: ['process', 'operations', 'sop', 'workflow', 'bottleneck', 'throughput', 'handover'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Write the SOP from what actually happened', 'Find where work queues up'],
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    domain: 'project-management',
    role: 'Delivery',
    charter: 'Keeps commitments honest and dependencies visible.',
    capabilityIds: ['operations', 'development'],
    matches: ['project', 'deadline', 'milestone', 'sprint', 'delivery', 'timeline', 'blocked'],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: ['Re-plan when a date slips instead of hoping', 'Make the critical path explicit'],
  },
  {
    id: 'automation',
    name: 'Automation Engineer',
    domain: 'automation',
    role: 'Removing repeated work',
    charter: 'Automates the third time you do something, not the first.',
    capabilityIds: ['automation', 'operations'],
    matches: [
      'automate',
      'automation',
      'automat',
      'workflow',
      'trigger',
      'recurring',
      'every week',
      'repetitive',
      'integrate',
    ],
    allowedScopeKinds: ['company', 'personal'],
    wouldDo: [
      'Turn a repeated sequence into an automation with an approval gate',
      'Measure the minutes actually returned',
    ],
  },
  {
    id: 'support',
    name: 'Customer Support Lead',
    domain: 'support',
    role: 'The customer’s voice',
    charter: 'Brings back what customers actually said, not what we wish they said.',
    capabilityIds: ['operations', 'sales', 'hr'],
    matches: ['support', 'customer', 'ticket', 'complaint', 'churn', 'feedback', 'onboarding'],
    allowedScopeKinds: ['company'],
    wouldDo: ['Cluster complaints into causes', 'Escalate the pattern, not the incident'],
  },
  {
    id: 'health',
    name: 'Performance Coach',
    domain: 'health',
    role: 'Body, recovery and energy',
    charter:
      'Treats sleep and recovery as inputs to the business, because for a founder they are.',
    capabilityIds: ['health'],
    matches: [
      'sleep',
      'slept',
      'energy',
      'tired',
      'exhausted',
      'fatigue',
      'recovery',
      'recover',
      'training',
      'workout',
      'stress',
      'health',
      'nutrition',
      'burnout',
      'rest',
    ],
    allowedScopeKinds: ['personal'],
    wouldDo: [
      'Read the week’s recovery before agreeing to a heavy schedule',
      'Protect the inputs that keep output possible',
    ],
  },
  {
    id: 'life-coach',
    name: 'Life Architect',
    domain: 'personal',
    role: 'Relationships, learning and life design',
    charter: 'Keeps the life the companies are supposed to be in service of.',
    capabilityIds: ['relationships', 'learning', 'life-ops'],
    matches: [
      'family',
      'friend',
      'relationship',
      'call',
      'birthday',
      'holiday',
      'travel',
      'personal',
      'life',
      'habit',
      'reading',
      'course',
    ],
    allowedScopeKinds: ['personal'],
    wouldDo: [
      'Notice who has not been contacted in too long',
      'Protect commitments that have no deadline but matter most',
    ],
  },
];

const BY_ID = new Map(SPECIALISTS.map((s) => [s.id, s]));

export function getSpecialist(id: string): SpecialistAgent | undefined {
  return BY_ID.get(id);
}

export function specialistName(id: string): string {
  return BY_ID.get(id)?.name ?? id;
}

export function specialistsForCapability(capabilityId: string): SpecialistAgent[] {
  return SPECIALISTS.filter((s) => s.capabilityIds.includes(capabilityId));
}

export function specialistsForScopeKind(kind: 'company' | 'personal'): SpecialistAgent[] {
  return SPECIALISTS.filter((s) => s.allowedScopeKinds.includes(kind));
}
